In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal

In [2]:
# Create the image
input_img = np.arange(1,17,1)
input_img = input_img.reshape(4,4)

# Create the Kernel
kernel  = np.array([[1,0,-1],[2,0,-2],[1,0,-1]])

input_img

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
kernel

array([[ 1,  0, -1],
       [ 2,  0, -2],
       [ 1,  0, -1]])

In [4]:
signal.convolve2d(input_img, kernel, "same")

array([[ 10,   6,   6, -13],
       [ 24,   8,   8, -28],
       [ 40,   8,   8, -44],
       [ 38,   6,   6, -41]])